"""add created_at to user

Revision ID: 222642daa844
Revises: f45b22a89702
Create Date: 2026-05-14 16:32:01.186296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222642daa844'
down_revision = 'f45b22a89702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
