"""notification table

Revision ID: 44072016e924
Revises: c733e411f604
Create Date: 2026-05-13 15:04:32.335661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44072016e924'
down_revision = 'c733e411f604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_discussion_parent_id',
            'discussion',
            ['parent_id'],
            ['id'],
        )

    with op.batch_alter_table('quiz_upvote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_upvote_quiz_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_upvote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_upvote_quiz_id'), ['quiz_id'], unique=False)

    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discussion_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    # ### end Alembic commands ###
