"""add pdf_cache to file_model

Revision ID: 7fca7ee26c53
Revises: c521e27e942b
Create Date: 2026-05-14 09:48:57.985192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fca7ee26c53'
down_revision = 'c521e27e942b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_cache', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_model', schema=None) as batch_op:
        batch_op.drop_column('pdf_cache')

    # ### end Alembic commands ###
