"""empty message

Revision ID: 803924669398
Revises: f4b1beac1433
Create Date: 2026-05-12 22:46:00.189437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803924669398'
down_revision = 'f4b1beac1433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mimetype', sa.String(length=100), nullable=True),
    sa.Column('file', sa.BLOB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_model_course_code'), ['course_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_model_course_code'))

    op.drop_table('file_model')
    # ### end Alembic commands ###
