"""one review per person

Revision ID: f45b22a89702
Revises: 7fca7ee26c53
Create Date: 2026-05-14 12:01:04.895558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45b22a89702'
down_revision = '7fca7ee26c53'
branch_labels = None
depends_on = None


def upgrade():
    # ── Remove duplicate reviews before adding the unique constraint ──────
    # Keep only the most recent review per (user_id, course_code) pair.
    # We do this in raw SQL so it works without SQLAlchemy models.
    import sqlalchemy as sa
    conn = op.get_bind()

    # Find the id to KEEP for each (user_id, course_code) — the newest one
    keepers = conn.execute(sa.text("""
        SELECT MAX(id) as keep_id
        FROM review
        WHERE user_id IS NOT NULL
        GROUP BY user_id, course_code
    """)).fetchall()

    keeper_ids = [row[0] for row in keepers]

    # Delete every review that is NOT a keeper and has a user_id
    # (NULL user_id rows are anonymous and can't violate the constraint)
    if keeper_ids:
        placeholders = ",".join(str(i) for i in keeper_ids)
        conn.execute(sa.text(f"""
            DELETE FROM review
            WHERE user_id IS NOT NULL
            AND id NOT IN ({placeholders})
        """))

    # ── Now safe to add the unique constraint ─────────────────────────────
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_review_user_course',
            ['user_id', 'course_code']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_user_course', type_='unique')

    # ### end Alembic commands ###
